name: auto-actions # 触发 workflow 的事件

on:
  push:
    branches:
      - main
  schedule:
    - cron: "20 23 * * *"
    # 每天9.30 '30 9 * * *'
    # 每小时执行 '0 * * * *'

# 一个workflow由执行的一项或多项job
jobs:
  # 一个job任务，任务名为 run-autoSignIn
  run-autoSignIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main #采用main分支下的

      - name: Setup Node.js #新建一个名为Setup Node.js的步骤
        uses: actions/setup-node@v2 #安装node.js
        with:
          node-version: "14"

      - name: Install Dependency
        run: |
          npm install
          npm install got
          npm install tough-cookie         

      - name: Run Auto SignIn
          env:
          COOKIES: ${{ secrets.COOKIES }}    
          QQ_SENDER: ${{ secrets.QQ_SENDER }}
          node ./index.js  #脚本存在根目录scripts文件夹下
